"""Eliminar Foreign Key de usuarios.panaderia_id

Revision ID: 18a0a79b1f78
Revises: 6fa948f24230
Create Date: 2026-08-04 17:55:03.503838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a0a79b1f78'
down_revision = '6fa948f24230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('configuracion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuracion_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
