"""Agregar tabla depositos_bancarios

Revision ID: 51c3e4ee9df1
Revises: 
Create Date: 2025-12-01 14:27:12.405305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c3e4ee9df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos_fijos', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('pagos_individuales', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('saldos_banco', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos_banco', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('pagos_individuales', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('activos_fijos', schema=None) as batch_op:
        batch_op.alter_column('panaderia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
