"""Inicializar migraciones - estructura completa

Revision ID: 6fa948f24230
Revises: 
Create Date: 2026-08-02 09:04:49.789534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa948f24230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_panaderia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panaderia_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('nombre_panaderia', sa.String(length=200), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('tipo_licencia', sa.String(length=20), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('ventas_ilimitadas', sa.Boolean(), nullable=True),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.Column('estado_suscripcion', sa.String(length=20), nullable=True),
    sa.Column('dias_gracia', sa.Integer(), nullable=True),
    sa.Column('ultima_notificacion', sa.DateTime(), nullable=True),
    sa.Column('notificaciones_pendientes', sa.Integer(), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('email_facturacion', sa.String(length=120), nullable=True),
    sa.Column('telefono_facturacion', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_cierre', sa.Date(), nullable=True),
    sa.Column('sistema_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('configuracion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuracion_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('configuracion_panaderia', schema='public')
    # ### end Alembic commands ###
