"""Agregar tenant_id a Usuario

Revision ID: 72038a929890
Revises: e2b3ddacc7bc
Create Date: 2026-08-06 14:02:24.944970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72038a929890'
down_revision = 'e2b3ddacc7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
