"""Activar panaderia_id en Panaderia

Revision ID: e2b3ddacc7bc
Revises: 18a0a79b1f78
Create Date: 2026-08-06 10:21:52.892303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b3ddacc7bc'
down_revision = '18a0a79b1f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panaderias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panaderia_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panaderias', schema=None) as batch_op:
        batch_op.drop_column('panaderia_id')

    # ### end Alembic commands ###
